import type { InstrumentId, InstrumentMeta, EffectId } from './types'

export const INSTRUMENTS: Record<InstrumentId, InstrumentMeta> = {
  piano: {
    id: 'piano',
    category: 'sampled',
    playMode: 'note',
    icon: '🎹',
    available: true,
    realm: 'keyboard',
    range: { low: 'A0', high: 'C8' },
    defaultKey: 'C',
    defaultScale: 'major',
    articulations: ['legato', 'staccato'],
    hasQuarterTones: false,
    description: 'Salamander grand piano — sampled, polyphonic, full 88-key range.',
  },
  electricPiano: {
    id: 'electricPiano',
    category: 'synth',
    playMode: 'note',
    icon: '🎼',
    available: true,
    realm: 'keyboard',
    range: { low: 'C2', high: 'C7' },
    defaultKey: 'C',
    defaultScale: 'major',
    articulations: ['legato'],
    hasQuarterTones: false,
    description: 'Wurli-style FM e-piano — sampled bell tones, soft sustain.',
  },
  guitar: {
    id: 'guitar',
    category: 'synth',
    playMode: 'note',
    icon: '🎸',
    available: true,
    realm: 'string',
    range: { low: 'E2', high: 'E5' },
    defaultKey: 'E',
    defaultScale: 'minor',
    articulations: ['pluck', 'strum-down', 'strum-up'],
    hasQuarterTones: false,
    description: 'Classical nylon guitar — Soundfont samples, 6-string fingerboard.',
  },
  bass: {
    id: 'bass',
    category: 'synth',
    playMode: 'note',
    icon: '🎚️',
    available: true,
    realm: 'synth',
    range: { low: 'E1', high: 'C4' },
    defaultKey: 'E',
    defaultScale: 'minor',
    articulations: ['pluck'],
    hasQuarterTones: false,
    description: 'Saw-wave mono bass with filter envelope.',
  },
  pad: {
    id: 'pad',
    category: 'synth',
    playMode: 'note',
    icon: '🌫️',
    available: true,
    realm: 'synth',
    range: { low: 'C2', high: 'C6' },
    defaultKey: 'C',
    defaultScale: 'minor',
    articulations: ['legato'],
    hasQuarterTones: false,
    description: 'Slow-attack FM pad — long swells, lush release.',
  },
  lead: {
    id: 'lead',
    category: 'synth',
    playMode: 'note',
    icon: '⚡',
    available: true,
    realm: 'synth',
    range: { low: 'C3', high: 'C7' },
    defaultKey: 'C',
    defaultScale: 'major',
    articulations: ['legato', 'staccato'],
    hasQuarterTones: false,
    description: 'Saw lead with subtle vibrato — solo synth voice.',
  },
  organ: {
    id: 'organ',
    category: 'synth',
    playMode: 'note',
    icon: '⛪',
    available: true,
    realm: 'keyboard',
    range: { low: 'C2', high: 'C6' },
    defaultKey: 'C',
    defaultScale: 'major',
    articulations: ['legato'],
    hasQuarterTones: false,
    description: 'Drawbar-style FM organ with fast attack and full sustain.',
  },
  drums: {
    // Internal id stays 'drums' so saved sessions / multiplayer state /
    // beat-maker patterns from older versions still resolve. The user-
    // facing label moved to "Beats" in i18n (audio.instrument.drums =
    // "Beats"). When the new full-kit "Real Drums" voice lands in a
    // later phase it'll get its own id ('realDrums') instead of fighting
    // with this one.
    id: 'drums',
    category: 'percussion',
    playMode: 'sample',
    icon: '🥁',
    available: true,
    samples: ['kick', 'snare', 'hihat', 'hihatO', 'clap', 'tom', 'ride'],
    realm: 'percussion',
    articulations: ['hit'],
    hasQuarterTones: false,
    description: 'TR-808 trigger box — kick, snare, hat, clap, tom, ride samples.',
  },
  violin: {
    id: 'violin',
    category: 'synth',
    playMode: 'note',
    icon: '🎻',
    available: true,
    realm: 'bowed',
    range: { low: 'G3', high: 'E6' },
    defaultKey: 'D',
    defaultScale: 'minor',
    articulations: ['down-bow', 'up-bow', 'legato', 'short', 'long', 'tremolo', 'pizzicato'],
    hasQuarterTones: true,
    description: 'Bowed violin — swipe across the strings to bow, tap to pluck. Maqam-aware fingerboard with quarter-tone positions.',
  },
  realDrums: {
    id: 'realDrums',
    category: 'percussion',
    playMode: 'sample',
    icon: '🥁',
    available: true,
    samples: ['kick', 'snare', 'hihatC', 'hihatO', 'ride', 'crash', 'tom1', 'tom2', 'floor'],
    realm: 'percussion',
    articulations: ['hit'],
    hasQuarterTones: false,
    description: 'Full acoustic drum kit — kick, snare, hats, toms, ride, crash. Velocity-sensitive hits.',
  },
  harmonica: {
    id: 'harmonica',
    category: 'synth',
    playMode: 'note',
    icon: '🎶',
    available: true,
    realm: 'wind',
    range: { low: 'C4', high: 'C7' },
    defaultKey: 'C',
    defaultScale: 'major',
    articulations: ['blow', 'draw'],
    hasQuarterTones: false,
    description: '10-hole diatonic harmonica — pick the key, blow / draw to play.',
  },
  oud: {
    id: 'oud',
    category: 'synth',
    playMode: 'note',
    icon: '🪕',
    available: true,
    realm: 'string',
    range: { low: 'C2', high: 'C5' },
    defaultKey: 'D',
    defaultScale: 'minor',
    articulations: ['pluck', 'strum-down', 'strum-up', 'tremolo'],
    hasQuarterTones: true,
    description: 'Arabic oud — six courses, quarter-tone fingerboard. Tap to pluck, swipe across courses to risha-strum.',
  },
  cello: {
    id: 'cello',
    category: 'synth',
    playMode: 'note',
    icon: '🎻',
    available: true,
    realm: 'bowed',
    range: { low: 'C2', high: 'A4' },
    defaultKey: 'D',
    defaultScale: 'minor',
    articulations: ['down-bow', 'up-bow', 'legato', 'short', 'long', 'tremolo', 'pizzicato'],
    hasQuarterTones: true,
    description: 'Bowed cello — bigger neck, deeper resonance, slower bow response. Same maqam-aware fingerboard as the violin.',
  },
  glitch: {
    id: 'glitch',
    category: 'fx',
    playMode: 'note',
    icon: '🌀',
    available: true,
    realm: 'fx',
    range: { low: 'C3', high: 'C6' },
    articulations: ['burst'],
    hasQuarterTones: false,
    description: 'Pink-noise burst through a bit-crusher — one-shot glitch FX.',
  },
  meme: {
    id: 'meme',
    category: 'fx',
    playMode: 'sample',
    icon: '📣',
    available: false,
    samples: ['airhorn', 'bruh', 'vine', 'trombone', 'windows', 'oof'],
    realm: 'fx',
    articulations: ['hit'],
    hasQuarterTones: false,
    description: 'Meme one-shots (coming later — sample pack pending).',
  },
}

export const INSTRUMENT_ORDER: readonly InstrumentId[] = [
  'piano',
  'electricPiano',
  'guitar',
  'violin',
  'cello',
  'oud',
  'harmonica',
  'bass',
  'pad',
  'lead',
  'organ',
  'drums',
  'realDrums',
  'glitch',
  'meme',
]

export const EFFECT_ORDER: readonly EffectId[] = [
  'reverb',
  'delay',
  'distortion',
  'chorus',
  'filter',
  'bitcrusher',
  'compressor',
]

export const DEFAULT_TEST_NOTES = [
  'C4',
  'D4',
  'E4',
  'F4',
  'G4',
  'A4',
  'B4',
  'C5',
] as const

const CHROMATIC = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'] as const

function noteRange(lowOctave: number, highOctave: number): string[] {
  const out: string[] = []
  for (let o = lowOctave; o <= highOctave; o++) {
    for (const n of CHROMATIC) out.push(`${n}${o}`)
  }
  return out
}

const NOTE_RANGES: Record<InstrumentId, readonly string[]> = {
  piano: noteRange(2, 6),
  electricPiano: noteRange(3, 5),
  guitar: noteRange(2, 5),
  bass: noteRange(1, 3),
  pad: noteRange(2, 5),
  lead: noteRange(4, 6),
  organ: noteRange(2, 5),
  drums: [],
  violin: noteRange(3, 6),
  cello: noteRange(2, 4),
  oud: noteRange(2, 5),
  harmonica: noteRange(4, 6),
  realDrums: [],
  glitch: noteRange(3, 5),
  meme: [],
}

export function noteOptionsFor(id: InstrumentId): readonly string[] {
  return NOTE_RANGES[id]
}

export const DEFAULT_NOTE_FOR: Record<InstrumentId, string> = {
  piano: 'C4',
  electricPiano: 'C4',
  guitar: 'E3',
  bass: 'E2',
  pad: 'C3',
  lead: 'C5',
  organ: 'C4',
  drums: 'kick',
  violin: 'D4',
  cello: 'D3',
  oud: 'D3',
  harmonica: 'C4',
  realDrums: 'kick',
  glitch: 'C4',
  meme: 'airhorn',
}
